### ISSUE TITLE
ThutPerms does not check group pems if default level is ALL.

### ISSUE THREAD

**Issue by AshleyWinston** [Thutmose/ThutPerms#11]
Hi guys,

I'm forwarding the following issue from the author of "Faction Mod" (https://minecraft.curseforge.com/projects/faction?gameCategorySlug=mc-mods&projectID=272919):

> Default permission level for factionmod.command.faction is set to ALL, and ThutPerms does not check group pems if default level is ALL. It checks group perms only if default level is set to OP, which is really weird ...
I let you see : https://github.com/Thutmose/ThutPerms/blob/master/src/main/java/thut/permissions/PermissionsManager.java#L36-L46
You can report this issue to its author

**Comment by Thutmose** [comment]
I can see about fixing that, that was added right when forge first made that permission level stuff, so I wasn't sure how it was to be handled.  Commands used an entirely different permissions checking, so it didn't affect anything during the testing.

**Comment by Thutmose** [comment]
Which minecraft version do you need this for?

**Comment by AshleyWinston** [comment]
1.12.

**Comment by Thutmose** [comment]
Just uploaded version 2.0.1 to curseforge, hopefully it fixes your issue.

**Comment by AshleyWinston** [comment]
Thank you.  I'll reply again in a few days, when I have a chance to update my server :-).

**Comment by Thutmose** [comment]
no problem, let me know if it works as you want it, I don't really use it much, so am not the best at testing functionality( this mod was made by request, I was sent a list of features, and I implemented them exactly as I was sent, the requester said it worked fine for what he needed, so I left it at that)

**Comment by AshleyWinston** [comment]
Okay, I tried the various versions, but FacMod spat out errors with 2.0.1 onwards.  It works with 2.0.0 if "all" is enabled for the group, but then all of the FacMod admin commands work as well.  Is it possible to have a "deniedCommands" permission set or something to deny these admin perms?
