### ISSUE TITLE
Can't get it to work :/

### ISSUE THREAD

**Issue by nikolajvj** [Thutmose/ThutPerms#15]
I've started a server with my friends, and this mod seems like the only mod, that potential could work out for us. When I am in the standard "mods" group everything works fine. However if I go into the "default" or a new group with the permissions set up. I can't use any commands at all, even the vanilla commands.
Here is what the console says, when I try to use any command:
https://pastebin.com/iUB9nh49

Hope someone can help.

**Comment by Thutmose** [comment]
I will look into fixing this when I get time, I am rather busy for the next few days, but hopefully I will be able to get time to work on some mod stuff later this week or so.

**Comment by nikolajvj** [comment]
Okay, Thank you so much. :)

**Comment by SilverDash** [comment]
Huh. Looks _almost_ similar to my own crash. Hopefully It's not _too_ similar.

**Comment by Thutmose** [comment]
it is a very similar crash, possibly the same cause, I still have not had a long enough period of free time to get to digging into the cause of the crash yet, I will keep both issues open incase they end up having different causes anyway

**Comment by SilverDash** [comment]
Sounds good. This just makes things much harder. This is the only mod I could find so far that supports 1.12. Lucky I'm only running a tiny server. Not too much of a big deal.
Good luck on your work and thank you for your time!

**Comment by Thutmose** [comment]
Try it with the jar I uploaded here: https://github.com/Thutmose/ThutPerms/issues/18 let me know if it works, or re-send crash log if it doesnt

**Comment by Thutmose** [comment]
this should be fixed as of the 2.0.4 which has been uploaded to curseforge
