### ISSUE TITLE
Server Crash: Server Start after initial creation of Permissions file. [Null Pointer]

### ISSUE THREAD

**Issue by SilverDash** [Thutmose/ThutPerms#16]
Server crashes after I start it a second time. It only happens when the permissions exist already.
Deleting the permissions folder and starting works just fine.

Here is the crash log: https://pastebin.com/V4rgGiB7

java.lang.NullPointerException: Exception in server tick loop

**Comment by Thutmose** [comment]
this is a duplicate of #15, I will get it fixed whenever i have time, which, hopefully will be sometime after thursday, until then, I am very busy with some other things, so don't have time to look into minecraft stuff.

**Comment by Thutmose** [comment]
Try it with the jar I uploaded here: https://github.com/Thutmose/ThutPerms/issues/18 let me know if it works, or re-send crash log if it doesnt

**Comment by Thutmose** [comment]
this should be fixed as of the 2.0.4 which has been uploaded to curseforge
