### ISSUE TITLE
Issue with /checkspawns permission node in pixelmon. 

### ISSUE THREAD

**Issue by jDinhBC** [Thutmose/ThutPerms#34]
Ive been trying to get this command to work /checkspawns for everyone on my server through the pixelmon mod. Recently they said they updated the glitch or bug with the permission node itself. But its still not working. Now I need help getting this to work. So far ive gotten the command nodes command.ivs (/ivs) and command.evs (/evs) to work but nothing else. /checkspawns is a base node with many sub commands nodes and im wondering if that has an issue with thutperms.  This are all the nodes  for this single command (/checkspawns: pixelmon.command.checkspawns
Allow checking normal spawns: pixelmon.checkspawns.normal
Allow checking cave rock block spawns: pixelmon.checkspawns.caverock
Allow checking fishing spawns: pixelmon.checkspawns.fishing
Allow checking Pixelmon grass spawns: pixelmon.checkspawns.grass
Allow checking headbutt spawns: pixelmon.checkspawns.headbutt
Allow checking legendary spawns: pixelmon.checkspawns.legendary
Allow checking mega boss spawns: pixelmon.checkspawns.megaboss
Allow checking rock smash spawns: pixelmon.checkspawns.rocksmash
Allow checking sweet scent spawns: pixelmon.checkspawns.sweetscent )
I've tried so many different variants of the node itself and nothing is working right now. I dont want to op anyone because if I did then they will all cheat. 

Edit. Other commands by the same pixelmon mod works  just not /checkspawns . I believe it to be a sub node issue.

Edit. /checkspawns shows up in the /help menu but it doesnt work instead it says  : you must be opped or have permission to use this command.

Heres a link to the pixelmon command nodes : https://pixelmonmod.com/wiki/index.php?title=Commands

**Comment by Thutmose** [comment]
use /editperms list to get the actual permissions nodes for the mod, I suspect they are different in this mod from what is in that list.

**Comment by jDinhBC** [comment]
sorry for the late reply, i did /editperms list and got the command.checkspawns as the node. and i tried it out, it shows up in /help but does not allow to use.
i sent a few picture to help idk what to do.

/
![checkspawns](https://user-images.githubusercontent.com/47726701/58674852-bc6d1100-831f-11e9-89f0-b773c76c3031.png)
![help](https://user-images.githubusercontent.com/47726701/58674855-becf6b00-831f-11e9-8584-25c31f636cf7.png)
![test](https://user-images.githubusercontent.com/47726701/58674858-c131c500-831f-11e9-96c9-cca1b7f1c14d.png)

**Comment by Thutmose** [comment]
do you have spongeforge, or any similar plugin systems? if so, thutperms won't work
