### ISSUE TITLE
[ThutPerms] - Custom permission for a command (other mod) ?

### ISSUE THREAD

**Issue by Finelarme9** [Thutmose/ThutPerms#37]
Hello

Thank you for your mod thutperms and thut-essentials. Your last release has fixed some bugs so thank you. I have a question regarding thutperms :

- I don't know what custom permission to write for a command of the mod https://minecraft.curseforge.com/projects/block-commands (allowing to affect command on block (left click/walk on)). The command looks like this = /commandcreate @Command:/give @p apple 1 @isClick @Bypass. **What permission should I add on the thut config files to allow the left click on the block (in a chunk claimed by someone else) please** ? The "walk on" feature works but not the "left click".

I already have wrote these permissions (in customcommand/thutperms.cfg and allowedCommands/thutperms.json) + add the block in white-list, but it doesn't work (I get the message "msg.team.deny", no matter if I am gm0/1/2/op) :

commandcreate:command.commandcreate / commandcreate:com.cxandy.BlockCommands.command.commandcreate / commandcreate:com.cxandy.BlockCommands.blockdatasave.command.commandcreate / commandcreate:com.cxandy.BlockCommands.capability.command.commandcreate / commandcreate:com.cxandy.BlockCommands.command.command.commandcreate / commandcreate:com.cxandy.BlockCommands.common.command.commandcreate_  

Thank you in advance for your help.
Ben

NB: Server/Client 1.12.2 - Forge 2830.

**Comment by Thutmose** [comment]
if you run `/editperms toggledebug`, then watch the console, it should list every permission being checked as it is being checked, can you update the issue with the results of that?

**Comment by Finelarme9** [comment]
It works! Thank you a lot. One little details below ("blockBreakWhitelist", not really a problem).
I have used /editPerms toggledebug + /editPerms list in console and have seen all permissions + add them like this (I will remove the unnecessary permissions later) :

**thutessentials.cfg**
```
land {
    S:blockBreakWhitelist <
	minecraft:stone => It seems that it's mandatory to add the block here (so the player can theoretically breaks the block but fortunately the mod "block-commands" disallow to break a block where a command has been applied. In all case it's possible to add a "tp command" on the block too, so the player is tp when he clicks. Double protection.
     >
    S:blockPlaceWhitelist <
	minecraft:stone
     >
    S:blockUseWhitelist <
	minecraft:stone
     >
```
 	 
**thutperms.cfg** 
```
# Custom mappings for permissions, the default shows an example for the give command [default: [give:minecraft.command.give]]
    S:customCommandPerms <
        give:minecraft.command.give
        commandadd:command.commandadd
        commandclear:command.commandclear
        commandcreate:command.commandcreate
        commanddel:command.commanddel
        commanddis:command.commanddis
        commandfind:command.commandfind
        commandremove:command.commandremove
        commandview:command.commandview
     >
```
 
**thutperms.json**	 
 ```
 "groups": [],
  "initial": {
    "name": "default",
    "prefix": "",
    "suffix": "",
    "members": [],
    "all": false,
    "all_non_op": true,
    "allowedCommands": [
      "command.commandadd",
      "command.commandclear",
      "command.commandcreate",
      "command.commanddel",
      "command.commanddis",
      "command.commandfind",
      "command.commandremove",
      "command.commandview",
	  "com.cxandy.BlockCommands.command.commandcreate", => Not sure if mandatory.
	  "com.cxandy.BlockCommands.blockdatasave.command.commandcreate", => Not sure if mandatory.
	  "com.cxandy.BlockCommands.capability.command.commandcreate", => Not sure if mandatory.
	  "com.cxandy.BlockCommands.command.command.commandcreate", => Not sure if mandatory.
	  "com.cxandy.BlockCommands.common.command.commandcreate" => Not sure if mandatory.
    ],
    "bannedCommands": []
  },	 
```

**Comment by Finelarme9** [comment]
I close this one. Thank you for your help!
