### ISSUE TITLE
Issue with commands and general usability (1.14.4)

### ISSUE THREAD

**Issue by Alkiasan** [Thutmose/ThutPerms#42]
Hi, same guy who had the issue with essentials and the lang file.
Assuming the same problem is happening here. commands like ./editgroup and ./groupinfo straight up don't exist on autofill, and running them results in an "Unknown command" error.
Interestingly, typing in ./edit comes up with this:
![image](https://user-images.githubusercontent.com/62717881/79165756-af43fe00-7ddb-11ea-9676-828b1e572f94.png)
Looking at this, it's the same layout as the lang files, so i'm assuming there's a problem with the lang file again?
Tried the same solution that fixed the essentials mod, where i put the lang file into the config folder, but this time it didn't work.

**Comment by Alkiasan** [comment]
commands autofill like this: 
![image](https://user-images.githubusercontent.com/62717881/79165853-e87c6e00-7ddb-11ea-9dab-f7fda936e36e.png)

And outputs come out like this: 
![image](https://user-images.githubusercontent.com/62717881/79165883-f3cf9980-7ddb-11ea-8f16-2ae743d96ba6.png)

**Comment by Thutmose** [comment]
try putting the mod on your client, or putting the json file for the localization in the config folder

**Comment by Thutmose** [comment]
the commands were completely re-written in 1.14.4+, so none of the old stuff applies anymore

**Comment by Alkiasan** [comment]
Thanks! Installing the mod clientside worked.
