### ISSUE TITLE
Cannot add permission of / checkspawns Pixelmon Reforged 8.1.2

### ISSUE THREAD

**Issue by Nxrding** [Thutmose/ThutPerms#45]
Hello. I can't add the permission to add the permission of Pixelmon's /checkspawns, I've tried to add all the permissions of the Pixelmon Reforged API and PixelmonMod and I still can't get permission, I've also tried other plugins permissions and mods and also nothing.

**Comment by Thutmose** [comment]
that mod does not use forge permissions api, thus is incompatible with a forge permission api manager
