### ISSUE TITLE
/editperms toggledebug doesn't work

### ISSUE THREAD

**Issue by jeffburggraf** [Thutmose/ThutPerms#48]
I can't get this command to work, either as a player (op) with the initial "/" or in the console without the "/".
I am getting,
              Unknown or incomplete command, see below for error
              editperms toggledebug

All other ThutPerms seem to work just fine.
Is this just me?

**Comment by Thutmose** [comment]
try setting `debug` to true in `thutperms-common.toml`, that mgiht work instead

**Comment by jeffburggraf** [comment]
That did it, thanks. 

The reason I ask is that I am not able to change the permissions of any Worldedit commands. It seems like maybe ThutPerms is not recognizing any Worldedit commands.

**Comment by Thutmose** [comment]
does worldedit support the Forge Permissions API? I didn't used to, and until it does, thutperms won't support it

**Comment by jeffburggraf** [comment]
Okay that makes sense. Thanks for all your hard work
