### ISSUE TITLE
【bug】CAN not stop the command of OP

### ISSUE THREAD

**Issue by blood789** [Thutmose/ThutPerms#52]
On the server, I set it like this：
{
  "groups": [],
  "initial": {
    "members": [],
    "name": "default",
    "prefix": "",
    "suffix": "",
    "all": false,
    "all_non_op": false,
    "allowedCommands": [],
    "bannedCommands": [],
    "permNumbers": {},
    "permStrings": {}
  },
  "mods": {
    "members": [],
    "name": "mods",
    "prefix": "",
    "suffix": "",
    **"all": flase,
    "all_non_op": false,**
    "allowedCommands": [],
    "bannedCommands": [],
    "permNumbers": {},
    "permStrings": {}
  }
}

When I set myself as an administrator in the Console, I can still open the creative mode. 
When I stop the server, I check the configuration file.

The symbol of “"all": flase,” in the "mods" change to "true" automatically！！！

I am making a hardcore modpacks, and I hope no one can cheat.
Can you fix this bug? 
Prevent administrators from executing instructions！

Thank you so much！

**Comment by blood789** [comment]
My version： 1.18.1
Forge：39.0.9

**Comment by Thutmose** [comment]
hmm, I will look into this, it shouldn't reset that if you changed it

**Comment by Thutmose** [comment]
[thutperms-1.18.1-5.0.1.jar.zip](https://github.com/Thutmose/ThutPerms/files/7801292/thutperms-1.18.1-5.0.1.jar.zip)

See if the version inside this zip makes any difference? It is inside the zip, as github comments do not allow .jar files directly

**Comment by blood789** [comment]
This version runs correctly.  You can upload to curseforge.

**Comment by blood789** [comment]
I tested in the following order.
1. Only add one mod, the default json file
1.1. Create a single player game, survival mode, and allow cheating. I can use command. (√)
1.2. Create a single player game and creative mode. I can use command. (√)

2. Only add one mod and modify it to all false.
2.1. Create a single player game, survival mode, and allow cheating. Cannot use command. (√)
2.2. Create a single player game, creative mode, and allow cheating. Cannot use command. (√)

3. For the server, only add one mod and modify it to all false.
3.1. To enter the game, it is not an op, and commands cannot be used. (√)
3.2. Set myself as an op. Cannot use command. (√)

4. Single player game. Put it in my modpackage. Modify it to all false. Turn off cheating detection from kubejs mod.
4.1. Create a single player game, survival mode, cheating is allowed. Cannot use command. (√)
4.2. Create a single player game and creative mode. Cannot use command. (√)

5. Server. Put it in my modpackage. Modify it to all false. Turn off cheating detection f from kubejs mod.
5.1. To enter the game, it is not an op, and cannot use commands. (√)
5.2. Set myself as an op. Cannot use command. (√)

6. The server starts cheating detection of kubejs mod.
6.1. To enter the game, it is not an op, and no commands can be used. (√)
6.2. Set yourself as an op. Cannot use command. (√)


In kubejs, I write as this.

onEvent('player.tick', event => {
    if (event.player.creativeMode || event.player.spectator)
           {
            event.server.runCommandSilent('gamemode survival @a')
            event.server.runCommandSilent('deop @a')
            event.server.runCommand('Donot cheat！没有权限！')
           }            
})

**Comment by Thutmose** [comment]
thanks for the comprehensive testing!

I have uploaded that version to curseforge.
