### ISSUE TITLE
Unable to Deny Perms when all_non_op is set to true

### ISSUE THREAD

**Issue by Arkhayla** [Thutmose/ThutPerms#53]
[Example Files.zip](https://github.com/Thutmose/ThutPerms/files/7825664/Example.Files.zip)

Minecraft Server/Client: 1.18.1
Forge 39.0.9
Thutperms 5.0.1

I am having problems with the permissions and I can't seem to figure out why
I have tried to deny_perm to players, groups, and no matter what they still seem to have access to the commands I deny
I've tried with in-game commands and via the json files

Troubleshooting via Discord revealed the problem likely lies in `all_non_op`
Thutmose — Today at 6:01 PM
> I am bringing up a local server to test on
> hmm, looks like there may be a bug in `all_non_op`
> so you might need to turn that to `false`, and then manually add the perms you need them to have

Arkhayla — Today at 6:09 PM
> That worked!

**Comment by Thutmose** [comment]
This should be fixed in 5.0.2, which has recently been uploaded to curseforge
