### ISSUE TITLE
Suggestion: Wildcards

### ISSUE THREAD

**Issue by JomiliDesign** [Thutmose/ThutPerms#9]
Hi thutmose,

it's more a question, but if answered with 'no' then it turns into a suggestion. ^^''

Does "ThutsPerms" support wildcards? What I mean is the following:
For example you have in Thut Essentials the permission "thut.essentials.commands.land.Create"
I'm lazy like everyone else - so if I want to give a certain group the entire permission of the section "land" (thut.essentials.commands.land) can I use the following syntax to solve this problem?

/editPerms Admins thut.essentials.commands.land.* true

The asterix after the dot would tell your permission mod to give every user of the group Admins access to all permissions of the section "land"?!

Like I said: If it's not part of the mod, would you like to implement such a cool feature?

Kind regards

**Comment by Thutmose** [comment]
I can look into adding this, it will require some changes to how it checks permissions, but it might be easily edited to accomodate.
